### ISSUE TITLE
RFC: packaging for brew installation

### ISSUE THREAD

**Issue by avsm** [moby/hyperkit#119]
I'm looking at creating a Homebrew package so that `brew install hyperkit` will install the binary.  We need a couple of changes to make this easier to do:

- tagged releases so we have stable tarballs in Homebrew with a sha256 hash.  We can address it directly via changeset, but a monotonically increasing version number is useful for the package manager.

- resources need to be downloaded by Brew and stored locally, so this makes the OPAM packaging slightly tricky.  We could cut a release tarball that vendors the various `mirage-block` packages needed, and does a local OCaml bootstrap (perhaps based on a cleaned up [opam-boot](https://github.com/avsm/opam-boot/blob/master/opam-boot).

I can work on the latter, but it would be good to get maintainer consensus on whether we are ok with tagging and releasing fully vendored tarballs that include the third-party sources from OPAM in one giant tarball that can be built standalone with just the Golang and OCaml compilers installed.

**Comment by samoht** [comment]
I like the idea. We could probably move all the related opam packages to `jbuilder` (or at least add `jbuild` files) to simplify the compilation of the big tarball. Which would probably mean that `jbuilder` should be packaged with `brew` too...

**Comment by avsm** [comment]
We could create a brew package of `jbuilder` that is independent of OPAM, so that it just installs the `jbuilder` binary.  Then the OCaml builds in the full tarball would just be a single pass. cc @diml to see if he has any objections to us creating a `jbuilder` Homebrew package.

**Comment by diml** [comment]
No objections on my side. Happy to see a Homebrew package for  jbuilder

**Comment by ijc25** [comment]
I'm happy for things to be tagged, I think GH will then just serve the tarball for us.

I suggest we use `0.YYYYMMDD` as the version for now rather than trying to decide what sorts of changes would warrant changing any given element of `x.y.z`.

**Comment by markeissler** [comment]
@ijc25 [SemVer](http://semver.org/) is pretty clear on how it should be applied. Using a non-standard versioning scheme is the bane of all modern software development IMHO. A roadmap would help layout major and minor numbers. The last digit is for patches which would be driven by regular bug releases. Whereas `0.YYYYMMDD` means what? An automated build just for the sake of it that may or may not actually affect any changes?

I'd say just start with tagging the last buildable commit with 0.1.0 right now (clearly hyperkit is usable but probably not near a 1.0.0 yet).

@avsm I was just getting ready to build a tap formula and am surprised there's no tagging here.

**Comment by samoht** [comment]
> I'd say just start with tagging the last buildable commit with 0.1.0 right now (clearly hyperkit is usable but probably not near a 1.0.0 yet).

Given it is used in production in Docker for Mac, I'd say we should just tag 1.0.0.

**Comment by rneugeba** [comment]
We don't really have a road map for features and we tend to add features/apply bug fixes as needed and then integrate and ship them. Because of that, I'm not sure release versioning ala SemVer makes much sense. However, tagging in some form probably would  make sense so that we can get the github tarball releases as @ijc25 suggested, but also to indicate which commits got shipped.

**Comment by markeissler** [comment]
Hrmm. Well, lack of a roadmap still doesn't mean you can't use SemVer X.y.z:

X - Major update, breaks backwards compatibility
y - Minor update, new feature, preserves backwards compatibility
z - Bug fix, preserves backwards compatibility

@avsm I currently have a brew formula in testing that builds head with...

```sh
>brew install hyperkit --head
```
The formula handles dependency installation (via existing brew formulae) and OPAM init as necessary.  There's no need for a tarball as proposed initially.

My strategy is to build bottles (pre-compiled binaries) for Yosemite onwards, `--head` would trigger a build of head off of master. I'd like to support a `--devel` release as well, which would build head off of a __develop__ branch but...well, looks like everything is just getting merged to master immediately right now.

So my proposal would be to at the very least implement git-flow on this repo so __master__ and __develop__ could be isolated.

**Comment by ijc25** [comment]
semver is fine for versioning specific APIs, I don't think it is quite so obvious that it works for an overall project which consists of many APIs and it is not at all clear what people think it means to apply semver versioning to hyperkit as a whole.

I would be fine with applying semver to something like the go bindings or other similar wrapper libraries.

I am not happy with applying semver to the CLI, that should never be maintained as a stable API IMHO and using any sort of version of the form x.y.z would give the misleading impression that it had some sort of semver style guarantees.

I am unclear whether semver would make sense for the emulated hardware abstractions or support for specific hardware virtualisation features exposed by the underlying platform.

@markeissler you appear to be asking for a far more heavy weight release process and scheme than I think we are realistically going to be putting in place for a project of this size and scope. IMHO we can probably commit to occasionally tagging something on master when we think it is a mostly reasonable state for people to use. I'm afraid I do not think we are going to go for `master` vs `develop` branches or anything like that.

**Comment by rneugeba** [comment]
I completely agree with @ijc25 regarding SemVer for HyperKit and would also be happy with occasional tagging of a non-SemVer variety. I also don't see the need for branches at the current state of the project. Given the current churn, tagging stable releases and develop in master seems fine.

**Comment by markeissler** [comment]
>  IMHO we can probably commit to occasionally tagging something on master when we think it is a mostly reasonable state for people to use.

@ijc25 So master isn't necessarily stable? If it is, then I could see creating builds off of the latest commit on master, using the commit or date or something to generate a version numbers to satisfy home-brew. Is that reasonable?

**Comment by ijc25** [comment]
@markeissler `master` is generally pretty stable in practice, and our goal is for it to always be releasable but of course there is always the possibility of unintentional breakage.

So doing builds from `master` seems ok to me, not sure if it is possible to query circleci to at least pick the latest master which was successfully tested or not.

**Comment by markeissler** [comment]
I could probably configure an alternate CI stream on Travis across OSX Yosemite onwards, then push artifacts out to Bintray for distribution.

**Comment by avsm** [comment]
It's not quite clear to me what the difference between `--devel` and `--HEAD` is... does the devel one install the stable version with development headers?

**Comment by markeissler** [comment]
Yeah, no, `--devel` in the brew installer sense has nothing to do with traditional Linux naming of packages. From the docs:

> Formulae can specify alternate downloads for the upstream project’s devel release (unstable but not master/trunk) or head (master/trunk).

Without an actual __develop__ branch on this project, the `--devel` install can't be supported. So that brings us to, really, what is the difference between `--HEAD` and `stable`?

So in brew formulas, `stable` is always produced from a snapshot not pulled from the VCS. This is why you'll often see the `stable` download url pointing back to a release on GitHub or (more often) to an url pointing to [Bintray](https://bintray.com), the route I'm taking.

`--HEAD` always has a download url pointing back to the VCS, that is, a Git repo url. Whereas `--HEAD` would always result in a build on the user's machine, `stable` would only result in a build if requested or if a pre-compiled binary (known as __bottles__) was not available for the platform (meaning the version of MacOS). __bottles__ are usually made available so that users don't have to install toolchain dependencies.

The difference between `--HEAD` and `stable` builds (on the user's machine) is that the former would build from a Git clone, but the latter would build from a source snapshot; therefore, it is possible that `--HEAD` can be ahead of the snapshot even though they're both ultimately pulling from master.

With that said, getting back to the tagging discussion with @rneugeba and @ijc25, I've decided to create version numbers that combine date and commit sha1: 20170515-fa78d94. This appears when running `hyperkit -v` and also when running `brew info hyperkit`. No tagging needed, with a human readable datestamp and the sha1 for accuracy.

This is what it looks like right now:

```sh
Jonys-Mac:hyperkit-test jonytest$ hyperkit -v
hyperkit: 20170515-fa78d94

Homepage: https://github.com/docker/hyperkit
License: BSD

Jonys-Mac:hyperkit-test jonytest$ brew info hyperkit
markeissler/hyperkit/hyperkit: stable 20170515-fa78d94, HEAD
A toolkit for embedding hypervisor capabilities in your application
https://github.com/moby/hyperkit
/usr/local/Cellar/hyperkit/20170515-fa78d94 (5 files, 272KB) *
  Built from source on 2017-05-18 at 12:42:18
From: /usr/local/Homebrew/Library/Taps/markeissler/homebrew-hyperkit/Formula/hyperkit.rb
==> Dependencies
Required: opam ✔, libev ✔
Jonys-Mac:hyperkit-test jonytest$
```

Building, installation and even testing (booting tinylinux and running an expect script) all work, although I'm not sure if Travis would support booting a VM within a VM. Still need to work out some tooling for automation.

**Comment by markeissler** [comment]
Happy to say that my initial work for the [homebrew-hyperkit](https://github.com/markeissler/homebrew-hyperkit) project is now available for some testing. Instructions are in the README but basically:

```sh
prompt> brew tap markeissler/hyperkit
prompt> brew install hyperkit
```

This will install a pre-compiled binary (known as a __bottle__ in brew terms). Binaries have been made available for Yosemite, El Capitan and Sierra.

The install can be tested (after installation) with:

```sh
prompt> brew test -vd hyperkit
```

That will download a pre-patched Tiny Core Linux 8.0 kernel and initrd, boot the system, wait for a prompt and shutdown the instance. It'll fly by pretty quickly.

**Comment by ijc25** [comment]
Thanks @markeissler!

Will the `brew tap markeissler/hyperkit` step eventually disappear? (I'm not familiar with how brew's repos are structured).

Do you need anything more from the hyperkit project?

**Comment by markeissler** [comment]
In order for that `brew tap` step to disappear, I believe/think that this one particular Homebrew requirement needs to be met:

> has a stable, tagged version (i.e. not just a GitHub repository with no versions)

As discussed previously (above), tagging and official "stable" versions are just not how this project is maintained at the moment.

I have everything I need from the hyperkit project. I just need to setup some automation for handling updates. Strategy is to build a new release whenever master is updated. Which may or may not be excessive....I could just build weekly and if anyone needs a more frequent release they could just `brew install hyperkit --head`.

**Comment by rneugeba** [comment]
@markeissler thanks for putting this together.

As mentioned above, I'd be more than happy to add tags for releases. The current tip has been shipping with Docker for Mac so could be considered a "release" @ijc25 WDYT? Should we maybe tag them with a date to avoid any confusion with SemVer?

**Comment by ijc25** [comment]
Tagging $something is fine with me, a recent version which has been shipped in d4m seems like as good a $something as anything.

I'm also keen to avoid something which looks like SemVer since it would be misleading, given that then the date seems as good as anything. I've a slight preference for `0.DATE` rather than just pure `DATE` so that if we want to transition to a "proper" versioning scheme at some point we haven't burnt the first 2017 major versions.

I think its probably moot if we can tag something, but would it have been possible to setup our CI to publish things such that `brew tap docker/hyperkit` is a thing?

**Comment by markeissler** [comment]
Of course, switching to a "proper" versioning scheme from the one proposed (`0.DATE`) wouldn't be impacted by the old format at all if the old one didn't include two decimal points. So `DATE` or `0.DATE` are equivalent because they're not `X.y.z`. The only problem I can see with using just `DATE` or `0.DATE` is that you can only use that tag once per day, which is why I had added the short SHA1. But if you're never going to tag more than once per day it doesn't matter.

Regarding CI. With a tagged version things are simplified dramatically. GitHub will begin offering archives under "releases". A release url will then replace the `url` in this part of the formula:

```rb
  stable do
    url "https://dl.bintray.com/markeissler/homebrew/hyperkit/hyperkit-20170515-fa78d94.tar.gz"
    ...
  end
```
CI will need to update that url and its `sha256` for each release, then create a pull request to brew. Bottles (precompiled binaries) will then be produced by the [brew test bot](https://github.com/Homebrew/brew/blob/master/docs/Brew-Test-Bot.md) automatically. Just need to figure out if there's a way to restrict system architectures for the bottles.

Finally, the whole "tap" thing can then go away and users will be able to `brew search hyperkit` and `brew install hyperkit` just like that.

**Comment by ijc25** [comment]
> Of course, switching to a "proper" versioning scheme from the one proposed (0.DATE) wouldn't be impacted by the old format at all if the old one didn't include two decimal points.

You seem to be inferring that "proper" == "SemVer", which is not necessarily the case and there are (of course) other "proper" versioning schemes which would consider `20170531` as newer that `1.0` e.g.:
```
$ dpkg --compare-versions 20170531 '>>' 1.0 && echo true || echo false
true
$ dpkg --compare-versions 0.20170531 '>>' 1.0 && echo true || echo false
false
```

WRT CI what I meant was whether we could run the process which produces the content at https://dl.bintray.com/markeissler/homebrew/hyperkit at a moby/hyperkit project controlled location, rather than have our homebrew stuff have a bus factor of 1.

**Comment by markeissler** [comment]
> You seem to be inferring that "proper" == "SemVer",

I was looking at this strictly from a lexical parsing perspective where something that has decimals is simply different from something that does not, and the "old" versioning scheme could be detected just based on the syntax (not the values themselves).

WRT CI, that url would be replaced by the GitHub release url for the tagged version. It's automatically offered by GitHub when you tag...

```rb
  stable do
    url "https://github.com/moby/hyperkit/archive/0.20170515.tar.gz"
    ...
  end
```

CI just needs to clone the [homebrew-core](https://github.com/Homebrew/homebrew-core), update the hyperkit formula's `stable` section with updated release url and the updated `sha256` which has to be calculated.

Aside: For the tap I had to create the archive in question because it didn't exist and that's what brew uses to build a package if a bottle doesn't exist for a platform; that is, brew will not pull from git to build a package unless the user specifically requests that `HEAD` be built.

**Comment by ijc25** [comment]
I have just pushed tags for the following corresponding to the d4m releases back to and including the last stable (in docker release terms) 17.03:
* `v0.20170214` = fe014d879e811ac30f83429286607b08150fe945 (17.03)
* `v0.20170227` = 31ca915ad98f8308265ef2393618b46f4db8dad6 (17.04)
* `v0.20170425` = a9c368bed6003bee11d2cf646ed1dcf3d350ec8c (17.05)

17.06 rc1 used 272951d647566a657ee63b2e8da309b176dfe129 which I will tag as v0.20170511 when 17.06 GA is released, assuming the version isn't bumped in the meantime (if it is I'll tag based on that).

There's some more stuff in master still (https://github.com/moby/hyperkit/compare/272951d647566a657ee63b2e8da309b176dfe129...master) which I expect will be used in 17.07 and which can be tagged when that happens.
