### ISSUE TITLE
Excessive CPU usage locks up Docker

### ISSUE THREAD

**Issue by simtel12** [moby/hyperkit#247]
Docker diagnostic ID: 81D7F1CE-28DA-4B33-9A1E-4AEC22C7F351/20190301231412

We run 2 docker containers on a Mac mini (Late 2014).  Current OS version is 10.12.6.

One of the containers is a low-traffic daemon that watches for Amazon SQS messages.  This one does not cause issues.  

The other is a moderate-traffic Jenkins instance.  At least once a week - but recently it's been every 2-3 days - every container within Docker will stop.  If we're lucky, lightweight, static pages can still be served from Jenkins, but anything that has to go to disk for info will not respond.  The com.docker.hyperkit process remains pegged at 200% CPU.  Sometimes this is paired with a high fseventsd CPU, but not usually.  If fseventsd is high, then eventually the container will start responding again.  While the CPU is pegged, we're unable to start containers, or do something like `docker exec -it -u 1000 androidjenkins bash`.

At the same time, I usually observe high memory usage in either/both `com.docker.osxfs` and/or `kernel_task`.  Occasionally I've observed very high memory usage in hyperkit -  but usually not.

I've finally gotten approval to upload the diagnostics, so I've included the one for the latest event.  Please help - we're getting close to abandoning Docker due to this.

**Comment by simtel12** [comment]
CPU usage pegged.
![screen shot 2019-03-01 at 3 35 27 pm](https://user-images.githubusercontent.com/4183233/53672541-df602a00-3c37-11e9-8460-4a02911e29df.png)
Memory usage while CPU is pegged.
![screen shot 2019-03-01 at 3 36 06 pm](https://user-images.githubusercontent.com/4183233/53672542-df602a00-3c37-11e9-904c-072bde028664.png)
Configuration
![screen shot 2019-03-01 at 3 36 44 pm](https://user-images.githubusercontent.com/4183233/53672543-df602a00-3c37-11e9-9942-af488514e1bf.png)

Note, in this particular event, the memory does not actually look problematic., but attempting any action with the containers via the command line (stop, exec, etc) hangs indefinitely.

**Comment by berwyn** [comment]
I've got the same thing going on my end, where HyperKit is listed as using approximately half the CPU I've allocated to it and then all commands hang. This is most notable using Docker Compose, where it will output an error message because its API requests timeout:

```
ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).
```

In these instances, I end up being forced to restart Docker for macOS (and thence HyperKit) because it never seems to recover.

**Comment by 0xdevalias** [comment]
I'm pretty consistently seeing `com.docker.hyperkit` locked at 50%+ CPU usage:
![image](https://user-images.githubusercontent.com/753891/54500679-6705a280-4973-11e9-87dd-9af39e274190.png)

This seems to happen even after reboot, even when nothing is particularly running.

macOS Mojave 10.14.3 (18D109)

Docker Desktop Community Version 2.0.0.3 (31259)

```
⇒  docker --version
Docker version 18.09.2, build 6247962

⇒  ls -la `which hyperkit`
/usr/local/bin/hyperkit -> /Applications/Docker.app/Contents/Resources/bin/com.docker.hyperkit*

⇒  hyperkit -v
hyperkit: v0.20180403-17-g3e954c
```

**Comment by hegarg** [comment]
I have got a similar problem and also excessive memory usage with one container running with 2 GB memory.

![image](https://user-images.githubusercontent.com/36055526/61990033-f0448880-b07b-11e9-88c1-fdd2f5b2d959.png)

```Docker version 18.09.2, build 6247962
hyperkit -v
hyperkit: v0.20180403-17-g3e954c

Homepage: https://github.com/docker/hyperkit
License: BSD

**Comment by nicolaskristoffersen** [comment]
Same issue. Docker need to be restarted and work is interrupted and/or lost.

hyperkit: v0.20190201-11-gc0dd46
Homepage: https://github.com/docker/hyperkit
License: BSD

Docker for Mac 2.1.0.1 (37199)
Engine: 19.03.1

Removal of all entries under Preferences -> File Sharing seems to solve this temporarily. Unfortunately after a while com.docker.hyperkit ends up using all available CPU power and becomes unresponsive again.

<img width="493" alt="billede" src="https://user-images.githubusercontent.com/1420929/63219193-decb3980-c16c-11e9-8295-d8cc822d8dc6.png">

**Comment by nicolaskristoffersen** [comment]
Issue reported on 18 Aug was related to a Dropbox isses with symlinks or (old) iCould files. Dropbox would keep syncronizing using up all resources which apparently made Docker go into an endless loop. Docker could then be restarted, but would at some point become unreachable again. The solution was to stop Dropbox syncronization while using Docker. It iseems like the newest version of Dropbox does not create this issue. However, if you experience issues with Docker and you are using Dropbox, try exiting Dropbox. Also you could search for files in Dropbox that are symlinks or iCould-files and romove those.

**Comment by justincormack** [comment]
Please report Docker issues to https://github.com/docker/for-mac/issues unless you have specifically diagnosed an issue in hyperkit that you can reproduce in a standalone way as hypervisor issues. These issues are related to file sharing which is not part of hyperkit.

**Comment by enozero** [comment]
@justincormack All signs are pointing back to the original issue being a hyperkit issue. The hyperkit process is getting pegged 2-4x above the CPU (200%-400%). A lot of other issues have been lumped into this one (like the Dropbox one), which may or may not be relevant to the original issue. Many of us do not have Dropbox installed, yet the issue still happens.

This is also a community-reported issue. Many folks do not have the technical knowledge to dive into the specifics of how hyperkit works directly with the osMac file system. I hope that ask to the community is not dissuade from filing issues unless the issue can be exactly pinpointed to hyperkit, as issues may never be filed due to the technical background needed to isolate and reproduce in a standalone way.

Our hope is that someone from the hyperkit team (or someone with some extensive knowledge in this are) may be able to help reproduce this issue so that a fix can be made. This is a well-documented issue on the Docker for Mac issues:

* https://github.com/docker/for-mac/issues/3499
* https://github.com/docker/for-mac/issues/3539
* https://github.com/docker/for-mac/issues/3894
* And more...

**Comment by justincormack** [comment]
hyperkit CPU usage reflects the usage of the virtual machine, that just means that you are using 2-4 cores on the guest VM, or potentially doing a lot of VM exits. It is not an indication of issues in hyperkit. If there are multiple issues open elsewhere, then opening one here does not help.
