### ISSUE TITLE
Support for MacOS Big Sur new Virtualization.framework

### ISSUE THREAD

**Issue by RobberPhex** [moby/hyperkit#317]
The new [Virtualization.framework](https://developer.apple.com/documentation/virtualization) support memory-balloon, it could save physical memory for hyperkit.

**Comment by rn** [comment]
Hyperkit uses the Hypervisor Framework and can't easily use bits from the virtualisation framework. Instead it would need to be  rewritten...well a lot of code would need deleting since there is a lot of duplication. 

However, looks like newer docker desktop versions have an option for using the virt framework instead of hyerperkit. I don't know if they plan to utilise memory overcommit/baloon

**Comment by djs55** [comment]
For Docker Desktop, feel free to add a ticket requesting memory ballooning (or the use of less memory) on the public roadmap: https://github.com/docker/roadmap

For Hyperkit as @rn says I don't think it's practical to use a mix of Hypervisor.framework and Virtualization.framework. It's probably possible to implement ballooning solely within the existing Hypervisor.framework, but I don't know if anyone has any plans to do that.
